= Handling Errors
:description: Errors are inevitable. Rust offers several flexible approaches to handling them.
:page-toclevels: 2
:page-aliases: handling-error-conditions.adoc

[abstract]
{description}

The developer's job is to be prepared for whatever is likely to come up -- and to try and be prepared for anything that conceivably could come up.
Couchbase gives you a lot of flexibility, but it is recommended that you equip yourself with an understanding of the possibilities.

How errors are actually returned (e.g. via `Try`, `Future`, or `Mono`) and handled are covered xref:concurrent-async-apis.adoc[here], so this document will focus instead on specific errors, along with a broader look at error handling strategies.

== Error Model

The {name-sdk} tries to make handling errors as easy as possible, whilst also attaching as much useful information as possible to the error to aid in debugging.
Errors are a wrapper around a accessible `ErrorKind` enum, and an opaque `ErrorContext`.
The `ErrorKind` is large enum containing a wide variety of error types, but most likely you will only want to handle a subset of them based on your requirements.

== Key-Value Errors

The KV Service exposes several common errors that can be encountered - both during development, and to be handled by the production app.
Here we will cover some of the most common errors.

If a particular key cannot be found it is returned as a `DocumentNotFound`:

[source,rust]
----
include::devguide:example$src/kv_operations.rs[tag=replace-document-not-found,indent=0]
----

[source,rust]
----
include::devguide:example$src/kv_operations.rs[tag=get-document-not-found,indent=0]
----

On the other hand if the key already exists and should not (e.g. on an insert) then it is raised as a `DocumentExists`:

[source,rust]
----
include::devguide:example$src/kv_operations.rs[tag=insert-exists,indent=0]
----

=== Concurrency

Couchbase provides optimistic concurrency using CAS (xref:howtos:concurrent-document-mutations.adoc[Compare and Swap]).
Each document gets a CAS value on the server, which is changed on each mutation.
When you get a document you automatically receive its CAS value.
When replacing the document, if you provide that CAS the server can check that the document has not been concurrently modified by another agent in-between.
If it has, it returns `CasMismatch`, and the most appropriate response is to simply retry it:

[source,rust]
----
include::devguide:example$src/kv_operations.rs[tag=cas-mismatch,indent=0]
----

=== Ambiguity

There are situations with any distributed system in which it is simply impossible to know for sure if the operation completed successfully or not.
Take this as an example: your application requests that a new document be created on Couchbase Server.
This completes, but, just before the server can notify the client that it was successful, a network switch dies and the application's connection to the server is lost.
The application can drop the operation future, but it's ambiguous to the app whether the operation succeeded or not.

Another ambiguous error is `DurabilityAmbiguous`, which can returned when performing a durable operation.
This similarly indicates that the operation may or may not have succeeded --
though when using durability you are guaranteed that the operation will either have been applied to all replicas, or none.

Given the inevitability of ambiguity, how is the application supposed to handle this?

It really needs to be considered case-by-case, but the general strategy is to become certain if the operation succeeded or not, and to retry it if required.

For instance, for inserts, they can simply be retried to see if they fail on `DocumentExists`, in which case the operation was successful:

[source,rust]
----
include::devguide:example$src/kv_operations.rs[tag=durability-ambiguous,indent=0]
----

That example is much closer to what an application will want to be doing.
Let's flesh it out further.

=== Real-World Error Handling

The application can write wrappers so that it can easily do operations without having to duplicate the error handling each time.
Something like this:

[source,rust]
----
include::devguide:example$src/kv_operations.rs[tag=insert-real,indent=0]
----

This will make a 'best effort' to do the insert (though its retry strategy is rather naïve, and applications may want to implement a more sophisticated approach involving exponential backoff and circuit breaking.)

If that best effort fails, and the `do_insert` call still returns a `Error`, then it's highly context-dependent how to handle that.
Examples would include displaying a "please try again later" error to a user, if there is one, and logging it for manual human review.
The application must make a suitable call for each case.

The application can write similar wrappers for the other operations -- replace, upsert, _et al_.
Note that the logic is a little different in each case:
for inserts, we confirm if the operation has already been successful on an ambiguous result by checking for `DocumentExists`
But this wouldn't make sense for an upsert.

=== Idempotent and Non-Idempotent Operations

TIP: Idempotent operations are those that can be applied multiple times and only have one effect.
Repeatedly setting an email field is idempotent -- increasing a counter by one is not.

Some operations we can view as idempotent as they will fail with no effect after the first success -- such as inserts.

Idempotent operations are much easier to handle, as on ambiguous error results (`DurabilityAmbiguous` or timeouts) the operation can simply be retried.

Most key-value operations are idempotent.
For those that aren't, such as a Sub-Document `array_append` call, or a counter increment, the application should, on an ambiguous result, first read the document to see if that change was applied.

== Customizing the RetryStrategy

A custom `RetryStrategy` can be provided on `ClusterOptions`  (so it will take effect globally):

[source,rust]
----
include::devguide:example$src/retries.rs[tag=global,indent=0]
----

Or it can be applied on a per-request basis:

[source,rust]
----
include::devguide:example$src/retries.rs[tag=request,indent=0]
----

Both approaches are valid, although we recommend for most use cases to stick with the defaults and only to override it on a per requests basis.

If you find yourself overriding every request with the same different strategy, it can make sense to apply it locally in order to DRY it up a bit.
There are no performance differences with both approaches, but make sure that even if you pass in a custom one on every request that you do not create a new one each time but rather share it across calls.

[source,rust]
----
include::devguide:example$src/retries.rs[tag=shared,indent=0]
----

While it is possible to implement the `RetryStrategy` from scratch, we *strongly recommend* that instead the `BestEffortRetryStrategy` is embedded and to only the specifiy `RetryReasons` that need to be customized are handled.
In practice, it should look something like this:

[source,rust]
----
include::devguide:example$src/retries.rs[tag=custom,indent=0]
----

One important rule is that you should never block inside `should_retry`, since it is called on the hot code path and can considerably impact performance.

If you need to call out to third party systems over the network or the file system to make retry decisions, we recommend that you do this from a different thread and communicate via atomics, for example, so that the hot code path only needs to do cheap lookups.

The `RetryAction` indicates what should be done with the request: if you return `None`, the orchestrator will cancel the request, resulting in the underlying error being returned.
The other option is to provide an action with `RetryAction::new(duration: Duration)`, indicating the duration when the request should be retried next.
This allows you to customize not only _if_ a request should be retried, but also _when_.

IMPORTANT: Not retrying operations is considered safe from a data-loss perspective.
If you are changing the retry strategy of individual requests keep the semantics discussed in <<Idempotent vs. Non-Idempotent Requests>> in mind.
You can check if a request is idempotent through the `is_idempotent()` function on `RetryRequest`, and also check if the `RetryReason` allows for non-idempotent retry through `allows_non_idempotent_retry()`.
If in doubt, check the implementation of the `BestEffortRetryStrategy` for guidance.

== Query and Analytics Errors

A {sqlpp} (formerly N1QL) query either returns results or an error as the same way as KV, like so:

[source,rust]
----
include::devguide:example$src/queries.rs[tag=errors,indent=0]
----

== Additional Resources

Errors & Exception handling is an expansive topic.
Here, we have covered examples of the kinds of exception scenarios that you are most likely to face.
More fundamentally, you also need to weigh up xref:concept-docs:durability-replication-failure-considerations.adoc[concepts of durability].

Diagnostic methods are available to check on the xref:health-check.adoc[health of the cluster], and the xref:tracing-from-the-sdk.adoc[health of the network].

Logging methods are dependent upon the platform and SDK used.
We offer xref:collecting-information-and-logging.adoc[recommendations and practical examples].

We have a xref:ref:error-codes.adoc[listing of error messages], with some pointers to what to do when you encounter them.



