= Data Operations
:description: Data service offers the simplest way to retrieve or mutate data where the key is known. Here we cover CRUD operations, document expiration, and optimistic locking with CAS.
:page-aliases: document-operations.adoc
:page-toclevels: 2

[abstract]
{description}
Here we cover CRUD operations, document expiration, and optimistic locking with CAS.

At its heart Couchbase Server is a high-performance key-value store, and the key-value interface outlined below is the fastest and best method to perform operations involving single documents.

A _document_ refers to an entry in the database (other databases may refer to the same concept as a _row_).
A document has an ID (_primary key_ in other databases), which is unique to the document and by which it can be located.
The document also has a value which contains the actual application data.
See xref:concept-docs:documents.adoc[the concept guide to _Documents_] for a deeper dive into documents in the Couchbase Data Platform.

Before proceeding, make sure you're familiar with the basics of authorization and connecting to a Cluster from the xref:hello-world:start-using-sdk.adoc[Start Using the SDK] section.

[TIP]
The Query Service can also be used to perform many single-document operations, but we very strongly recommend using the key-value API for this instead.
It can be much more efficient as the request can go directly to the correct node, there's no query parsing overhead, and it's over the highly optimized memcached binary protocol.

== Upsert

Here is a simple upsert operation, which will insert the document if it does not exist, or replace it if it does.

[source,rust]
----
include::devguide:example$src/kv_operations.rs[indent=0,tag=upsert]
----

// == Handling Single Errors

[NOTE]
.Handling Single Errors
====
We will use `println` to simply print any errors in these samples, but the application will of course want to perform better error handling.
====


== Insert

Insert works very similarly to upsert, but will fail if the document already exists:

[source,rust]
----
include::devguide:example$src/kv_operations.rs[indent=0,tag=insert]
----

== Retrieving Documents

We've tried upserting and inserting documents into Couchbase Server, let's get them back:

[source,rust]
----
include::devguide:example$src/kv_operations.rs[indent=0,tag=get]
----

Of course if we're getting a document we probably want to do something with the content:

[source,rust]
----
include::devguide:example$src/kv_operations.rs[indent=0,tag=insert-then-get]
----

Let's break down what's going on here.

We're using the `?` operator to propagate errors for brevity.

First, we create some JSON using `serde_json` and insert it.

Then, we get the document.

If it's successful, we convert the document's content into a `serde_json::Value`.

We can use `contentAs` to return the document's content in all sorts of ways: as a String, as an int, as a custom type; it's very flexible.
Here, we've asked for it to be returned as a `Value` -- a flexible way to handle JSON.

Finally, if the conversion to a `Value` was successful, we try to get the "status" field (which returns an `Option`), and print it if we were successful.

== Replace

A very common operation is to `get` a document, modify its contents, and `replace` it.


[source,rust]
----
include::devguide:example$src/kv_operations.rs[indent=0,tag=replace-with-cas]
----

There's a couple of things to cover with the `replace` line.

First, most of the methods in the {name-sdk} take option blocks that have sensible defaults.
One of them, `cas`, is provided here.
We'll see more throughout this document.

[#optimistic-locking]
=== What is CAS?

CAS, or Compare and Swap, is a form of optimistic locking.
Every document in Couchbase has a CAS value, and it's changed on every mutation.
When you `get` a document you also get the document's CAS, and then when it's time to write the document, you send the same CAS back.
If another agent has modified that document, the Couchbase Server can detect you've provided a now-outdated CAS, and return an error instead of mutating the document.
This provides cheap, safe concurrency.
See xref:concurrent-document-mutations.adoc[this detailed description of CAS] for further details.

In general, you'll want to provide a CAS value whenever you `replace` a document, to prevent overwriting another agent's mutations.

=== Retrying on CAS Failures

But if we get a CAS mismatch, we usually just want to retry the operation.
Let's see a more advanced `replace` example that shows one way to handle this:

[source,rust]
----
include::devguide:example$src/kv_operations.rs[indent=0,tag=replace-retry]
----

== Removing

Removing a document is straightforward:

[source,rust]
----
include::devguide:example$src/kv_operations.rs[indent=0,tag=remove]
----

== Sub-Document Operations

All of the operations seen so far involve fetching the complete document.

As an optimization the application may consider using the xref:subdocument-operations.adoc[Sub-Document API] to access or mutate specific parts of a document.

== Custom structs

So far we've used JSON directly with `Value`, but it can be very useful to deal with Rust structs instead.
The SDK operations will accept any type that implements `Serialize` for mutations, and any type that implements `DeserializeOwned` for retrievals.

== Durability

Writes in Couchbase are written initially to a single active node, and from there the Couchbase Server will take care of sending that mutation to any configured replicas.

The optional `durability_level` parameter, which all mutating operations accept, allows the application to wait until this replication is successful before proceeding.

It can be used like this:

[source,rust]
----
include::devguide:example$src/kv_operations.rs[indent=0,tag=remove-with-durability]
----

The default is to run without durability, in which the SDK will return as soon as Couchbase Server has the mutation available in-memory on the active node.
This is the default for a reason: it's the fastest mode, and the majority of the time is all the application needs.

However, we recognize that there are times when the application needs that extra certainty that especially vital mutations have been successfully replicated, and the other durability options provide the means to achieve this.

The options differ depend on what Couchbase Server version is in use.
If 6.5 or above is being used, you can take advantage of the xref:concept-docs:durability-replication-failure-considerations.adoc#durable-writes[Durable Write] feature, in which Couchbase Server will only return success to the SDK after the requested replication level has been achieved.
The three replication levels are:

`MAJORITY` -- The server will ensure that the change is available in memory on the majority of configured replicas.

`MAJORITY_AND_PERSIST_TO_MAJORITY` -- Majority level, plus persisted to disk on the active node.

`PERSIST_TO_MAJORITY` -- Majority level, plus persisted to disk on the majority of configured replicas.

The options are in increasing levels of failure-resistance.
Note that nothing comes for free -- for a given node, waiting for writes to storage is considerably slower than waiting for it to be available in-memory.
These trade offs, as well as which settings may be tuned, are discussed in the xref:concept-docs:durability-replication-failure-considerations.adoc#durable-writes[durability page].

To stress, durability is a useful feature but should not be the default for most applications, as there is a performance consideration, and the default level of safety provided by Couchbase will be reasonable for the majority of situations.

== Expiration/TTL

////
eventing is also a way to handle bulk deletes.  So is setting the expiration time.   If this is something like a daily purge, why not set the expiration time to the end of the day when the docs are being inserted?  If this is purging documents after they have been processed or transferred, why not delete (or expire) them as they are processed or transferred? (edited) 
////

Couchbase Server includes an option to have particular documents automatically expire after a set time.
This can be useful for some use-cases, such as user sessions, caches, or other temporary documents.

You can set an expiration value when creating a document:

[source,rust]
----
include::devguide:example$src/kv_operations.rs[indent=0,tag=insert-with-expiry]
----

When getting a document, the expiry is not provided automatically by Couchbase Server but it can be requested:

[source,rust]
----
include::devguide:example$src/kv_operations.rs[indent=0,tag=get-with-expiry]
----

Note that when updating the document, special care must be taken to avoid resetting the expiry to zero.
Here's how:

[source,rust]
----
include::devguide:example$src/kv_operations.rs[indent=0,tag=replace-with-preserve-expiry]
----

Some applications may find `getAndTouch` useful, which fetches a document while updating its expiry field.
It can be used like this:

[source,rust]
----
include::devguide:example$src/kv_operations.rs[indent=0,tag=get-and-touch]
----


// CAS
// https://www.couchbase.com/forums/t/how-many-leading-digits-of-the-cas-constitute-the-timestamp/32556/8
// not a guaranteed timestamp!



== Atomic Counter Operations

To support counter use-cases, a Couchbase document can be treated as an integer counter and adjusted or created atomically like this:

[source,rust]
----
include::devguide:example$src/binary.rs[indent=0,tag=counterexample]
----

Note that a counter cannot be below 0.

NOTE: Increment & Decrement are considered part of the 'binary' API and as such may still be subject to change

TIP: Setting the document expiry time only works when a document is created, and it is not possible to update the expiry time of an existing counter document with the Increment method -- to do this during an increment, use with the `Touch()` method.


// Atomicity Across Data Centers

include::{version-common}@sdk:shared:partial$atomic.adoc[tag=xdcr]


// Remove totally? All examples should now lead with collection level?
////
== Scoped KV Operations

It is possible to perform scoped key value operations on named xref:{version-server}@server:learn:data/scopes-and-collections.adoc[`Collections`] _with Couchbase Server release, 7.0_.

Here is an example showing an upsert in the `users` collection, which lives in the `travel-sample.tenant_agent_00` keyspace:

[source,scala]
----
include::devguide:example$scala/KvOperations.scala[indent=0,tag=named-collection-upsert]
----
////


== Additional Resources

Working on just a specific path within a JSON document will reduce network bandwidth requirements -- see the xref:subdocument-operations.adoc[Sub-Document] pages.

As well as various xref:concept-docs:data-model.adoc[Formats] of JSON, Couchbase can work directly with xref:concept-docs:nonjson.adoc[arbitrary bytes, or binary format].

Our xref:sqlpp-queries-with-sdk.adoc[Query Engine] enables retrieval of information using the SQL-like syntax of {sqlpp} (formerly N1QL).

