= Managing Connections
:description: This section describes how to connect the {name-sdk} to a Couchbase cluster.
// :page-aliases: ROOT:managing-connections,howtos:multi-network,ROOT:connecting,ROOT:connection-advanced
:page-toclevels: 2


// Note to editors
// 
// This page pulls in content from -sdk-common-
// and code samples from -example-dir-
// 
// It can be seen built at wwww.


[abstract]
{description}
It contains best practices as well as information on TLS/SSL and advanced connection options, and a sub-page on troubleshooting Cloud connections.

Our xref:hello-world:start-using-sdk[Getting Started pages] cover the basics of making a connection to a Capella or self-managed Couchbase cluster.
This page is a wider look at the topic.

== Connecting to a Cluster

A connection to a Couchbase Server cluster is represented by a `Cluster` object.
A `Cluster` provides access to buckets, scopes, and collections, as well as various Couchbase services and management interfaces.
The simplest way to create a `Cluster` object is to call `Cluster.connect()` with a <<connection-strings, connection string>> (or Capella endpoint), username, and password:

[tabs,sync-group-id="Couchbase Capella|Self-Managed Couchbase Server"]
==== 
Couchbase Capella::
+
--
[source,scala]
----
include::devguide:example$src/capella_sample.rs[tag=connect,indent=0]
----

Note, the client certificate for connecting to a Capella operational cluster is included in the SDK installation.
--

Self-Managed Couchbase Server::
+
-- 
[source,rust]
----
include::devguide:example$src/start_using.rs[tag=connect,indent=0]
----
--
====

In a production environment, your connection string should include the addresses of multiple server nodes in case some are currently unavailable.
Multiple addresses may be specified in a connection string by delimiting them with commas:

[source,rust]
----
include::devguide:example$src/start_using.rs[tag=multiple-endpoints,indent=0]
----

TIP: You don't need to include the address of every node in the cluster.
The client fetches the full address list from the first node it is able to contact.

=== Waiting for Bootstrap Completion

When `Cluster.connect` is called, the client begins bootstrapping the cluster connection, which includes fetching the cluster configuration and opening connections to all of the KV nodes.
Opening resources after initial `Cluster.connect` is asynchronous.
That is, the call to `cluster.bucket` will complete instantly, and opening that resource will continue in the background - for each bucket that you open the SDK will open a new set of KV connections and manage a different bucket configuration from the cluster.

You can force waiting for the resource to be opened with a call to `wait_until_ready`, which is available on both the `Cluster` and `Bucket`.
Here is an example of using it on the bucket:

[source,rust]
----
include::devguide:example$src/start_using.rs[tag=bucket-wait-until-ready,indent=0]
----

If not present, then the first Key Value (KV) operation on the bucket will wait for it to be ready.
Any issues opening that bucket (for instance, if it does not exist), will result in an error being returned from that data operation.

Other timeout issues may occur when using the SDK located geographically separately from the Couchbase Server cluster --
this is xref:project-docs:compatibility.adoc#network-requirements[not recommended in production deployments], but often occurs during development.
See the <<working-in-the-cloud,Cloud section>> below for some suggestions of settings adjustments.

=== Connection Strings

A Couchbase connection string is a comma-delimited list of IP addresses and/or hostnames, optionally followed by a list of parameters.

The parameter list is just like the query component of a URI; name-value pairs have an equals sign (`=`) separating the name and value, with an ampersand (`&`) between each pair.
Just as in a URI, the first parameter is prefixed by a question mark (`?`).

.Simple connection string with one seed node
----
127.0.0.1
----

.Connection string with two seed nodes
----
nodeA.example.com,nodeB.example.com
----

.Connection string with two parameters
----
127.0.0.1?io.networkResolution=external&timeout.kvTimeout=10s
----

The full list of recognized parameters is documented in the client settings reference.
Any client setting with a system property name may also be specified as a connection string parameter (without the `com.couchbase.env.` prefix).

=== Connection Lifecycle

Most of the high-level classes in the {name-sdk} are designed to be safe for concurrent use by multiple threads.
You will get the best performance if you share and reuse instances of `Cluster`, `Bucket`, `Scope`, and `Collection`, all of which are thread-safe.

We recommend creating a single `Cluster` instance when your application starts up, and sharing this instance throughout your application.
If you know at startup time which buckets, scopes, and collections your application will use, we recommend obtaining them from the `Cluster` at startup time and sharing those instances throughout your application as well.

When the `Cluster` is dropped all active connections to the Couchbase Server cluster will be closed and all resources will be released.
Any attempt to use any derived resources (buckets, scopes, collections, etc.) after the `Cluster` has been dropped will result in an error.

[#ssl]
== Secure Connections

Both Couchbase Capella, and the
xref:{version-server}@server:introduction:editions.adoc#enterprise-edition[Enterprise Edition] of self-managed Couchbase Server, support full encryption of client-side traffic using Transport Layer Security (TLS).
That includes data (key-value type) operations, queries, and configuration communication.
Make sure you have the Enterprise Edition of Couchbase Server, or a Couchbase Capella account, before proceeding with configuring encryption on the client side.

[{tabs}]
====
Couchbase Capella::
+
--
The {name-sdk} bundles Capella's standard root certificate by default.
This means you don't need any additional configuration to enable TLS -- simply use `couchbases://` in your connection string.

NOTE: Capella's root certificate is *not* signed by a well known CA (Certificate Authority).
However, as the certificate is bundled with the SDK, it is trusted by default.
--

Self-Managed Couchbase Server::
+
--
You can provide a certificate:

. Get the CA certificate from the cluster and save it in a text file.
. Enable encryption on the client side and point it to the file containing the certificate.

It is important to make sure you are transferring the certificate in an encrypted manner from the server to the client side, so either copy it through SSH or through a similar secure mechanism.

If you are running on `localhost` and just want to enable TLS for a development machine, just copying and pasting it suffices
-- _so long as you use `127.0.0.1` rather than `localhost` in the connection string_.
This is because the certificate will not match the name _localhost_.

// TODO: not entirely sure this is correct, need to check this.
//Setting `TLSSkipVerify` is a workaround if you need to use `couchbases://localhost`.

Navigate in the admin UI to menu:Settings[Cluster] and copy the input box of the TLS certificate into a file on your machine (which we will refer to as `cluster.cert`).
It looks similar to this:

----
-----BEGIN CERTIFICATE-----
MIICmDCCAYKgAwIBAgIIE4FSjsc3nyIwCwYJKoZIhvcNAQEFMAwxCjAIBgNVBAMT
ASowHhcNMTMwMTAxMDAwMDAwWhcNNDkxMjMxMjM1OTU5WjAMMQowCAYDVQQDEwEq
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzz2I3Gi1XcOCNRVYwY5R
................................................................
mgDnQI8nw2arBRoseLpF6WNw22CawxHVOlMceQaGOW9gqKNBN948EvJJ55Dhl7qG
BQp8sR0J6BsSc86jItQtK9eQWRg62+/XsgVCmDjrB5owHPz+vZPYhsMWixVhLjPJ
mkzeUUj/kschgQ0BWT+N+pyKAFFafjwFYtD0e5NwFUUBfsOyQtYV9xu3fw+T2N8S
itfGtmmlEfaplVGzGPaG0Eyr53g5g2BgQbi5l5Tt2awqhd22WOVbCalABd9t2IoI
F4+FjEqAEIr1mQepDaNM0gEfVcgd2SzGhC3yhYFBAH//8W4DUot5ciEhoBs=
-----END CERTIFICATE-----
----

The next step is to enable encryption and pass it the path to the certificate file.

[source,scala]
----
include::devguide:example$scala/ManagingConnections.scala[tag=secure,indent=0]
----

Then use this custom `ClusterEnvironment` when opening the connection to the cluster.
See <<cluster-environment>> for an example of creating a `Cluster` with a custom environment.

If you want to verify it's actually working, you can use a tool like [.cmd]`tcpdump`.
For example, an unencrypted upsert request looks like this (using `sudo tcpdump -i lo0 -A -s 0 port 11210`):

----
E..e..@.@.............+......q{...#..Y.....
.E...Ey........9........................id{"key":"value"}
----

After enabling encryption, you cannot inspect the traffic in cleartext (same upsert request, but watched on port 11207 which is the default encrypted port):

----
E.....@.@.............+....Z.'yZ..#........
..... ...xuG.O=.#.........?.Q)8..D...S.W.4.-#....@7...^.Gk.4.t..C+......6..)}......N..m..o.3...d.,.	...W.....U..
.%v.....4....m*...A.2I.1.&.*,6+..#..#.5
----
--
====

The SDK includes the certificate for Capella.
// , but you may wish to
// [use your own certificate], 
// or be
If you are working with a self-managed Couchbase cluster, add the certificate with:

[source,rust]
----
include::devguide:example$src/start_using.rs[tag=secure-connection,indent=0]
----

== Alternate Addresses and Custom Ports

If your Couchbase Server cluster is running in a containerized, port mapped, or otherwise NAT'd environment like Docker or Kubernetes, a client running outside that environment may need additional information in order to connect the cluster.
Both the client and server require special configuration in this case.

On the server side, each server node must be configured to advertise its external address as well as any custom port mapping.
This is done with the https://docs.couchbase.com/server/6.5/cli/cbcli/couchbase-cli-setting-alternate-address.html[`setting-alternate-address` CLI command] introduced in Couchbase Server 6.5.
A node configured in this way will advertise two addresses: one for connecting from the same network, and another for connecting from an external network.

On the client side, the externally visible ports must be used when connecting.
If the external ports are not the default, you can specify custom ports in the connection string.
The port where the data service is running must be specified

[source]
----
127.0.0.1:11299
----

In many cases the client is able to automatically select the correct set of addresses to use when connecting to a cluster that advertises multiple addresses.
// If the detection heuristic fails in your environment, you can override it by setting the `io.networkResolution` client setting to `default` if the client and server are on the same network, or `external` if they're on different networks.

NOTE: Any TLS certificates must be set up at the point where the connections are being made.


// DNS-SRV
// == Using DNS SRV records

include::{version-common}@sdk:shared:partial$dnssrv-pars.adoc[tag=dnssrv-rev]

DNS SRV bootstrapping is enabled by default in the {name-sdk}.
In order to make the SDK use the SRV records, you need to pass in the hostname from your records (here `example.com`):

////
[source,scala]
----
include::devguide:example$scala/ManagingConnections.scala[tag=dnssrv,indent=0]
----
////

If the DNS SRV records could not be loaded properly you'll get an error logged and the given host name will be used as a A record lookup.
Also, if you pass in more than one node, DNS SRV bootstrap will not be initiated:


== Working in the Cloud

include::{version-common}@sdk:shared:partial$managing-connections.adoc[tag=cloud]

== Next Steps

* xref:secure-connections.adoc[Certificate Authentication] 
