= Provisioning Cluster Resources
:description: Provisioning cluster resources is managed at the collection or bucket level, depending upon the service affected.
// :page-aliases: ROOT:managing-clusters
:page-toclevels: 2

:lang: Rust
:example-source: devguide:example$src/cluster_resources.rs
:example-source-lang: rust

[abstract]
{description}
Common use cases are outlined here, less common use cases are covered in the https://docs.couchbase.com/sdk-api/couchbase-rust-client/[API docs].

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=management-intro]

The {name-sdk} also comes with some convenience functionality for common Couchbase management requests.

include::{version-common}@sdk:shared:partial$provisioning-clusters.adoc[tag=not-capella]


// Management operations in the SDK may be performed through several interfaces.

// TODO Link to the relevant API reference pages once they are live
// * {bucket-api-reference}
// * {user-api-reference} -- see the xref:sdk-user-management-example.adoc[User Management page]
// * {query-api-reference}
// * {analytics-api-reference}
// * {search-api-reference}
// * {collection-api-reference}
// * {view-api-reference}

== Bucket Management

The `BucketManager` interface may be used to create and delete buckets from the Couchbase cluster.

`BucketSettings` is used for creating and updating buckets.
`BucketSettings` is also used for exposing information about existing buckets.

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=update-bucket-warning]

Here is the list of parameters available for `BucketSettings`.
The "Updatable" column indicates whether the parameter may only be specified when creating a bucket, or whether it may be updated after creation.

[cols="30,30,28,12"]
|====
| Name | Type | Description | Updatable

| `name` | `String` | The name of the bucket, required for creation. | false
| `ram_quota_mb` | `u64` | How much memory should each node use for the bucket, required for creation. | true
| `flush_enabled` | `bool` | Enables flushing to be performed on this bucket (see the <<Flushing Buckets>> section below). | true
| `num_replicas` | `u32` | The number of replicas to use for the bucket. | true
| `evictionPolicy` | `EvictionPolicyType` | The type of the eviction to use for the bucket, defaults to `ValueOnly`. | true (note: changing will cause the bucket to restart causing temporary inaccessibility)
| `max_expiry` | `Duration` | The default maximum time-to-live to apply to documents in the bucket. (note: This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.) | true
| `compressionMode` | `CompressionMode` | The compression mode to apply to documents in the bucket. (note: This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.) | true
| `minimum_durability_level` | `DurabilityLevel` | The durability level to be assigned to the bucket. | true
| `conflictResolutionType` | `ConflictResolutionType` | The conflict resolution type to apply to conflicts on the bucket, defaults to `SequenceNumber` | false
| `replica_indexes` | `bool` | Whether or not to replicate indexes. | false
| `bucket_type` | `BucketType` | The type of the bucket, required for creation. | false
| `storage_backend` | `StorageBackend` | The storage backend to be assigned to and used by the bucket. | true (note: additional steps required to migrate a bucket's storage backend. See https://docs.couchbase.com/server/current/manage/manage-buckets/migrate-bucket.html[Migrate a Bucket's Storage Backend] for more information)
| `num_vbuckets` | `u16` | The number of vBuckets for this bucket. | false
| `history_retention_collection_default` | `bool` | Whether a change history is made for the bucket. This parameter is ignored unless the storageBackend is set to `magma`.  | true
| `history_retention_collection_fault` | `bool` | Whether a change history is made for the bucket. This parameter is ignored unless the storageBackend is set to `magma`.  | true
| `history_retention_bytes` | `u64` | Specifies the maximum size, in bytes, of the change history that is written to disk for all collections in this bucket when the value of history_retention_collection_fault is true.  | true
| `history_retention_duration` | `Duration` | Specifies the maximum number of seconds to be covered by the change history that is written to disk for all collections in this bucket when the value of history_retention_collection_fault is true. | true
|====

The following example creates a "hello" bucket:

[source,rust]
----
include::devguide:example$src/cluster_resources.rs[tag=bucket,indent=0]
----

We can now get this bucket and update it to enable Flush:

[source,rust]
----
include::devguide:example$src/cluster_resources.rs[tag=flush,indent=0]
----

Once you no longer need to use the bucket, you can remove it:

[source,rust]
----
include::devguide:example$src/cluster_resources.rs[tag=drop,indent=0]
----

=== Flushing Buckets

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=flush-intro]

You can flush a bucket in the SDK by using the `Flush` method:

[source,rust]
----
include::devguide:example$src/cluster_resources.rs[tag=flush,indent=0]
----

== Collection Management

The CollectionManager interface may be used to create and delete scopes and collections from the Couchbase cluster.
It is instantiated through the `Bucket.collections()` method.
// TODO update once API reference is live
// Refer to the https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/manager/collection/index.html[`CollectionManager` and `AsyncCollectionManager` API documentation]
// for further details.

[source,rust]
----
include::devguide:example$src/cluster_resources.rs[tag=collections,indent=0]
----

You can create a scope:

[source,rust]
----
include::devguide:example$src/cluster_resources.rs[tag=create_scope,indent=0]
----

You can then create a collection within that scope:

[source,rust]
----
include::devguide:example$src/cluster_resources.rs[tag=create_collection,indent=0]
----

Finally, you can drop unneeded collections and scopes:

[source,rust]
----
include::devguide:example$src/cluster_resources.rs[tag=drop_collection,indent=0]

include::devguide:example$src/cluster_resources.rs[tag=drop_scope,indent=0]
----

Note that the most minimal permissions to create and drop a Scope or Collection is
xref:server:learn:security/roles.adoc#manage-scopes[Manage Scopes]
along with xref:server:learn:security/roles.adoc#data-reader[Data Reader].

You can create users with the appropriate RBAC programmatically:

[source,rust]
----
include::devguide:example$src/cluster_resources.rs[tag=scope_admin,indent=0]
----
// see also https://issues.couchbase.com/browse/CBSE-16834

== Index Management

In general, you will rarely need to work with Index Managers from the SDK.

// TODO: Update once API reference is live
// For those occasions when you do, index management operations can be performed with the following interfaces:
//
// * {query-api-reference}
// * {search-api-reference}

For those occasions when you do, you will find some of these described in the following section.

=== QueryIndexManager

The `QueryIndexManager` interface contains the means for managing indexes used for queries. +
It can be accessed via `Collection.query_indexes()`.

[source,rust]
----
include::devguide:example$src/cluster_resources.rs[tag=query_index_manager,indent=0]
----

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=query-index-manager-intro]

The example below shows how to create a simple primary index on the collection, by calling the `create_primary_index()` method.

.Creating a primary index
[source,rust]
----
include::devguide:example$src/cluster_resources.rs[tag=create_primary_index,indent=0]
----

When a primary index name is not specified, the SDK will create the index as `#primary` by default.
However, if you wish to provide a custom name, you can simply pass an `indexName` argument to `CreatePrimaryIndexOptions`.

You may have noticed that the example also sets the `ignoreIfExists` boolean flag.
When set to `true`, this optional argument ensures that an error is not thrown if an index under the same name already exists.

Creating a _secondary_ index follows a similar approach, with some minor differences:

.Creating a secondary index
[source,rust]
----
include::devguide:example$src/cluster_resources.rs[tag=create_secondary_index,indent=0]
----

The `create_index()` method requires an index name to be provided, along with the fields to create the index on.

Indexes can easily take a long time to build if they contain a lot of documents.
In these situations, it is more ideal to build indexes in the background.
To achieve this we can use the `deferred` boolean option, and set it to `true`.

.Deferring index creation
[source,rust]
----
include::devguide:example$src/cluster_resources.rs[tag=deferred_indexes,indent=0]
----

To delete a query index you can use the `drop_index()` or `drop_primary_index()` methods.
Which one you use depends on the type of query index you wish to drop from the cluster.

.Deleting an index
[source,rust]
----
include::devguide:example$src/cluster_resources.rs[tag=drop_indexes,indent=0]
----

// * Search - note & link to FTS page & API?

// backup and restore
////
This is not a service provided directly through the SDK, as it is easily achieved by using one of the following:

* `cbbackupmgr`.
* Invoke xref:server:rest-api:backup-rest-api.adoc[Backup/Restore API service] -- 
which can be done through `CouchbaseHttpClient`, using `HttpTarget.backup()`.
* xref:operator::concept-backup.adoc[Autonomous operator Backup/restore].
* xref:cloud:clusters:manage-backup.adoc[Capella Backup/restore].

The majority use case is to call a baackup from the commandline --
using `cbbackupmgr`, or a `curl` with the REST API.
////

