= User Management
:description: pass:q[The Rust SDK lets you create _users_, assign them _roles_ and associated _privileges_, and remove them from the system.]
:page-aliases: ROOT:sdk-user-management-example.adoc

[abstract]
{description}

== User-Management APIs

Users who have been assigned the *Admin* role for the cluster are able to create, edit, and remove users.
The SDK lets you programmatically create _users_, assign them _roles_ and associated _privileges_, and remove them from the system.

// A high-level summary of the APIs can be found in xref:concept-docs:sdk-user-management-overview.adoc[User-Management], and details of all options in the https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/manager/user/UserManager.html[UserManager API docs].

== Using the UserManager API

The most common uses of the `UserManager` API are administering users:

.Upserting Users
[source,rust]
----
include::devguide:example$src/user_management.rs[tag=upsertuser,indent=0]
----

.Listing Users
[source,rust]
----
include::devguide:example$src/user_management.rs[tag=getusers,indent=0]
----

.Removing Users
[source,rust]
----
include::devguide:example$src/user_management.rs[tag=removeuser,indent=0]
----

.Changing a password
[source,rust]
----
include::devguide:example$src/user_management.rs[tag=changepassword,indent=0]
----

NOTE: `change_password` applies to the user currently authenticated in the `Cluster` instance.

== Further Reading

The SDK also contains management APIs for dealing with xref:provisioning-cluster-resources.adoc[Cluster resources].
