= Slow Operations Logging
:description: Tracing information on slow operations can be found in the logs as threshold logging, orphan logging, and other span metrics.
:page-toclevels: 2

[abstract]
{description}
Change the settings to alter how much information you collect

To improve debuggability certain metrics are automatically measured and logged.
These include slow queries, responses taking beyond a certain threshold, and orphanned responses.

== Threshold Logging Reporting

Threshold logging is the recording of slow operations -- useful for diagnosing when and where problems occur in a distributed environment.


=== Configuring Threshold Logging

To configure threshold logging, adjust the xref:observability-tracing.adoc#the-thresholdloggingtracer[ThresholdRequestTracer].
You should expect to see output in JSON format in the logs for the services encountering problems:

[source,json]
----
{
  "<service-a>": {
    "total_count": 1234,
    "top_requests": [{<entry>}, {<entry>},...]
  },
  "<service-b>": {
    "total_count": 1234,
    "top_requests": [{<entry>}, {<entry>},...]
  },
}
----

The `total_count` represents the total amount of over-threshold recorded items in each interval per service. 
The number of entries in “top_requests” is configured by the `sampleSize`. 
The service placeholder is replaced with each service -- “kv”, “query”, etc. 
Each entry looks like this, with all fields populated:

[source,json]
----
{
    "total_duration_us": 6252,
    "encode_duration_us": 10,
    "last_dispatch_duration_us": 6159,
    "total_dispatch_duration_us": 6159,
    "operation_name": "upsert",
    "last_local_id": "4e459355-9550-45fb-b5f4-ea71f5d4d613",
    "last_remote_socket": "192.168.106.130:11210"
}
----

If a field is not present (because for example dispatch did not happen), it will not be included. 