= Querying with {sqlpp}
:description: You can query for documents in Couchbase using the {sqlpp} query language, a language based on SQL, but designed for structured and flexible JSON documents.
// :page-aliases: n1ql-query.adoc
:page-aliases: n1ql-queries-with-sdk.adoc
// :page-aliases: ROOT:document-operations.adoc,ROOT:documents-creating,ROOT:documents-updating,ROOT:documents-retrieving,ROOT:documents-deleting,n1ql-queries-with-sdk.adoc
:lang: Rust
:example-source: devguide:example$src/queries.rs
:example-source-lang: rust

[abstract]
{description}

On this page we dive straight into using the Query Service API from the {name-sdk}.
For a deeper look at the concepts, to help you better understand the Query Service, the {sqlpp} language, and the Index Service, see the links in the <<further-information,Further Information>> section at the end of this page.

include::howtos:partial$n1ql-intro.adoc[]
include::howtos:partial$n1ql-getting-started.adoc[]


// index first - start again - see both C++ and .NET versions....
// https://docs.couchbase.com/dotnet-sdk/current/howtos/n1ql-queries-with-sdk.html#querying-at-scope-level


Note that building indexes is covered in more detail on the xref:concept-docs:n1ql-query.adoc#index-building[Query concept page] --
and in the https://docs.rs/couchbase/latest/couchbase/management/query/query_index_manager/struct.QueryIndexManager.html#implementations[API Reference].

== A Simple Query

Here's the basics of how to run a simple query to fetch 10 random rows from travel-sample and print the results:

[source,rust]
----
include::devguide:example$src/queries.rs[tag=simple,indent=0]
----

(Note that we won't be covering the {sqlpp} language itself in any detail here, but if you're familiar with SQL you'll see it's very similar.)

The returned `QueryResult` contains a `rows[T]` method, allowing the results to be converted into something useful.
The above example demonstrates returning the results as `serde_json::Value`, a flexible way to handle JSON.

`rows` can be deserialized into any type that implements `serde::DeserializeOwned`.

// Please see xref:json.adoc[this guide] for more information on the supported ways of working with JSON.

include::howtos:partial$n1ql-placeholders.adoc[]
include::howtos:partial$n1ql-scan-consistency.adoc[]

And the `AtPlus` level is represented with `ScanConsistency.AtPlus`, combined with `consistent_with`:

[source,rust]
----
include::devguide:example$src/queries.rs[tag=atplus,indent=0]
----

== Returning Results as Your Own Type

The Rust SDK supports returning {sqlpp} results directly as Rust struct types.

A very small amount of boilerplate is required to tell the SDK how to convert your case class to/from JSON.
You can read more about `serde` https://serde.rs/[here], including how to customize the deserialization process.

[source,rust]
----
include::devguide:example$src/queries.rs[tag=deserialization,indent=0]
----

Now you're free to pull out the results directly as your type:

[source,rust]
----
include::devguide:example$src/queries.rs[tag=owntype,indent=0]
----

== Querying at Cluster Level

The code snippet below shows how to run a simple query to fetch 10 random rows from travel-sample and print the results.
Querying at the `Cluster` level without specifying a scope or collection means that the query is implicitly executed against the `_default` collection in the `_default` scope.

[source,rust]
----
include::devguide:example$src/queries.rs[tag=clusterlevelquery,indent=0]
----

// A complete list of `QueryOptions` can be found in the https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/query/QueryOptions.html[API docs].

include::howtos:partial$n1ql-additional-resources.adoc[]

// tutorial - https://query.pub.couchbase.com/tutorial/#1
// check it's working still?

// recursive
// https://www.couchbase.com/blog/recursive-query-processing-in-sql-n1ql/ 





// also
// query options
// https://github.com/couchbaselabs/sdk-rfcs/pull/125/files 



// == Further Information


