= Transcoders & Non-JSON Documents
:description: The {name-sdk} supports common JSON document requirements out-of-the-box.

[abstract]
{description}
Custom transcoders and serializers provide support for applications needing to perform advanced operations, including supporting non-JSON data.

The {name-sdk} uses the concepts of transcoders, which are used whenever data is sent to or retrieved from Couchbase Server.

When sending data to Couchbase, the SDK passes the object being sent to a transcoder.
The transcoder can either reject the object as being unsupported, or convert it into a `byte[]` and a Common Flag.
The Common Flag specifies whether the data is JSON, a non-JSON string, or raw binary data.

Transcoders in the {name-sdk} work a little differently to other SDKs.
The SDK exposes a number of `{operation-name}_raw` functions for supporting types that do not implement `Serialize` and/or should not be serialized to JSON using `serde_json`.
Transcoding with these functions occurs outside the function, to be idiomatic to the Rust ecosystem.
Owing to a lack of reflection in Rust, the transcoders implemented in the SDK do not work in the same way as other SDKs.
We'll explore how this works in the examples below.

On retrieving data from Couchbase, the fetched `byte[]` and Common Flag are passed to a transcoder.
The transcoder converts the bytes into a concrete type (the application specifies the required type) if possible.

NOTE: Many applications will not need to be aware of transcoders, as the defaults support most standard JSON use cases.
The information in this page is only needed if the application has an advanced use-case, likely involving either non-JSON data, or a requirement for a particular JSON serialization library.

== Default Behaviour

By default, the SDK will use `couchbase::transcoding::json` for serialization and deserialization, which leverages `serde_json`.

== RawJsonTranscoder

The RawJsonTranscoder provides the ability for the application to explicitly specify that the data they are storing or retrieving is JSON.
This transcoder always performs straight pass through of the data to the server.
This enables the application to avoid unnecessary parsing costs when they are certain they are using JSON data.

[source,rust]
----
include::devguide:example$src/transcoding.rs[tag=raw_json_transcoder,indent=0]
----

== Non-JSON Transcoders

It is most common to store JSON with Couchbase.
However, it is possible to store non-JSON documents, such as raw binary data, perhaps using an concise binary encoding like https://msgpack.org[MessagePack] or https://cbor.io/[CBOR], in the Key-Value store.

NOTE: It's important to note that the Couchbase Data Platform includes multiple components other than the Key-Value store -- including Query and its indexes, FTS, Analytics, and Eventing -- and these are optimized for JSON and will either ignore or provide limited functionality with non-JSON documents.

Also note that some simple data types can be stored directly as JSON, without recourse to non-JSON transcoding.
A valid JSON document can be a simple integer (`42`), string (`"hello"`), array (`[1,2,3]`), boolean (`true`, `false`) and the JSON `null` value.

=== RawStringTranscoder

The RawStringTranscoder provides the ability for the user to explicitly store and retrieve raw string data with Couchbase.
It can be used to avoid the overhead of storing the string as JSON, which requires two bytes for double quotes, plus potentially more for escaping characters.

[source,rust]
----
include::devguide:example$src/transcoding.rs[tag=raw_string_transcoder,indent=0]
----

=== RawBinaryTranscoder

The RawBinaryTranscoder provides the ability for the user to explicitly store and retrieve raw byte data to Couchbase.
The transcoder does not perform any form of real transcoding, and does not take a serializer, but rather passes the data through and assigns the appropriate binary Common Flag.

[source,rust]
----
include::devguide:example$src/transcoding.rs[tag=raw_binary_transcoder,indent=0]
----

== Custom Transcoders

More advanced transcoding needs can be accomplished if the application implements their own transcoders.

=== Creating a Custom Transcoder

Let's look at a more complex example: encoding the JSON alternative, https://msgpack.org[MessagePack].
MessagePack is a compact binary data representation, so it should be stored with the binary Common Flag.
The Common Flag is chosen by the transcoder, and none of the existing transcoders matches our needs (`raw_binary` does set the binary flag, but it passes data through directly rather than using a serializer).
So we need to write one.

Create a transcoder that uses the `rmp_serde` crate to serialize/deserialize and sets the binary Common Flag when storing the data:

[source,rust]
----
include::devguide:example$src/transcoding.rs[tag=msgpack,indent=0]
----

Note this transcoder is completely independent to MessagePack.
All it does is pass data to and from a serializer, and set a Binary Common Flag.

Now we can use the new transcoder to seamlessly store MessagePack data in Couchbase Server:

[source,rust]
----
include::devguide:example$src/transcoding.rs[tag=use_msgpack,indent=0]
----

== Further reading

// * For _Common flags_, setting the data format used, see the xref:concept-docs/data-model.html#data-structures
// ref:data-structures.adoc#common-flags[Data Structures reference].
// * _Format flags_ for ancient SDKs are still available for compatibility, if you are porting a long-lived legacy app.
// See the xref:ref:data-structures.adoc#legacy-formats[Legacy formats reference].
* If you want to work with binary documents and our Search service, you might like to take a look at https://github.com/khanium/couchbase-fts-binary




