= Compatibility
:description: Platform compatibility, and features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features
:page-toclevels: 3
:table-caption!:

[abstract]
{description}

The Couchbase {name-sdk} {sdk_dot_minor} Client supports Rust 1.90+.

== Platform Compatibility

=== OS Compatibility

The {name-sdk} is tested and supported on the following OSs and platforms:

****
[discrete]
=== GNU/Linux

* Amazon Linux 2 & AL2023.
* Red Hat Enterprise Linux 8 & 9;
* Oracle Linux 8 & 9.
* Ubuntu (LTS) 22.04 (_Jammy_) & 24.04 (_Noble_).
* Debian 11 (_Bullseye_) & Debian 12 (_Bookworm_).
* SUSE Enterprise Linux 12 & 15
* Alpine Linux 3.18 (_Oracle JDK only_) -- but see <<alpine-linux-compatibility, workaround note below>>.

[discrete]
=== Microsoft Windows

* Microsoft Windows 10 & 11;
* Windows Server 2019 & 2022.

[discrete]
=== Mac OS X

The current and previous two releases of OS X.
At time of writing (April 2025): 15 (Sequoia), 14 (Sonoma), and 13 (Ventura).
M1 ARM architecture is fully supported in the {name-sdk}.

[discrete]
=== ARM Processor Support

ARM64: support for ARMv8 CPUs, such as the Amazon Graviton series and Apple M1 ARM processors.
****

The {name-sdk} should also be expected to run on other commonly-available GNU/Linux distributions which support the Rust platform, but not all combinations can be tested.

// Network Requirements
include::{version-common}@sdk:shared:partial$network-requirements.adoc[]

== Couchbase Server Compatibility

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.

=== Couchbase Version/SDK Version Matrix

The matrix below denotes the version of Couchbase Server, the version of the Rust SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*: This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
|===
| | 1.0

| *Server 7.0 - 7.2*
| *✖*

| *Server 7.6 - 8.0*
| *✔*
|===


// ①
// ① Server 7.6 is compatible with all supported (not yet End-of-Life) versions of the {name-sdk}, but for full support of the latest features you need to upgrade to a recent version of the SDK.
// See the <<#couchbase-new-feature-availability-matrix,Feature Availablity matrix below>> and the xref:sdk-release-notes.adoc[Release Notes page].

Note the https://www.couchbase.com/support-policy/EOL/[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.

=== Capella Compatibility

The Couchbase {name_platform} SDK is fully compatible with Couchbase Capella, our fully-hosted database-as-a-service.
To make development easier, the SDK includes the Capella client certificate ready installed.

include::{version-common}@sdk:shared:partial$capella.adoc[tag=cloud]


// add in Columnar link

=== Couchbase New Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells]
[cols="7,6"]
|===
| | Server 7.6

| Enhanced Durability
| All SDK versions

| Durable Writes
| All SDK versions

| Analytics
| Not Supported

| Collections
| All SDK versions

| Scope-Level {sqlpp} (formerly N1QL) Queries & all Collections features
| All SDK versions

| Request Tracing
| Not Supported

| Cloud Native Gateway
| Not Supported

| Vector Search
| All SDK versions

| Vector Query
| All SDK versions
|===

This table is not an exhaustive list -- just a few highlights -- provided to help assess compatibility of older versions in particular.
For alignment of SDKs and new Server features, scroll down to the information below the <<api-version,API Version table>>.

=== API Version

include::{version-common}@sdk:shared:partial$api-version.adoc[tag=api-version]

== SDK API Stability

=== Interface Stability

include::{version-common}@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]

=== Older SDK Versions

include::{version-common}@sdk:shared:partial$archive.adoc[tag=link]
