= Couchbase Scala SDK Installation
:description: Installation instructions for the Couchbase Scala Client.
:navtitle: Full Installation
:page-partial:
:page-toclevels: 2

[abstract]
{description}


This page gives full installation instructions for the {name-sdk}.
In most cases, the xref:hello-world:start-using-sdk.adoc[Quickstart Guide] should be enough to get you up and running if you're in a hurry.


== Prerequisites

The {name-sdk} is tested against LTS versions of Oracle JDK and OpenJDK -- see our xref:project-docs:compatibility.adoc#jdk-compat[compatibility docs].

The Couchbase {name-sdk} 1.0 Client supports Rust 1.90+ and Edition 2024.


== Installing the SDK

The Couchbase {name-sdk} is available on crates.io.

To include it in your project, add the following to your `Cargo.toml`:

[source]
----
cargo add couchbase
----

== Further Reading

For those who spend little or no time using {name_platform}, but have to evaluate the platform, further installation and background help is available on the xref:hello-world:platform-help.adoc[{name_platform} Platform Introduction page].
