= Documents
:description: Couchbase supports CRUD operations, various data structures, and binary documents.
//:page-aliases: ROOT:core-operations
// :page-aliases: ROOT:documents,ROOT:documents-basics,ROOT:documents-atomic



[abstract]
{description}

Although query and path-based (Sub-Document) services are available, the simplicity of the document-based kv interface is the fastest way to perform operations involving single documents.


// use the simplicity of https://developer.couchbase.com/documentation/server/3.x/developer/dev-guide-3.0/read-write.html possibly?
// don't forget https://docs-staging.couchbase.com/dotnet-sdk/2.7/datastructures.html - and Java equiv?

////
== Documents

== Input and Output Types

== Counters

== Data Structures

== Raw Byte Concatenation
////


include::{version-common}@sdk:shared:partial$documents.adoc[tag=document]

== Primitive Key-Value Operations

[source,rust]
----
collection.upsert(docid, document, opts);
collection.insert(docid, document, opts);
collection.replace(docid, document, opts);
collection.get(docid, opts);
collection.remove(docid, opts);
----

include::{version-common}@sdk:shared:partial$documents.adoc[tag=crud-overview]

include::{version-common}@sdk:shared:partial$documents.adoc[tag=store-update]

[NOTE]
====
If you wish to only modify certain parts of a document, you can use xref:subdocument-operations.adoc[Sub-Document] operations which operate on specific subsets of documents:

[source,rust]
----
include::devguide:example$src/subdocument.rs[tag=upsert,indent=0]
----

or xref:{version-server}@server:n1ql:n1ql-language-reference/update.adoc[N1QL UPDATE] to update documents based on specific query criteria:

[source,n1ql]
----
update `default` SET sale_price = msrp * 0.75 WHERE msrp < 19.95;
----
====

include::{version-common}@sdk:shared:partial$documents.adoc[tag=get_generic]

[source,n1ql]
----
SELECT * FROM default USE KEYS ["docid"];
----

or

[source,n1ql]
----
SELECT * FROM default WHERE META(default).id = "docid";
----

You can also retrieve _parts_ of documents using xref:subdocument-operations.adoc[Sub-Document operations], by specifying one or more sections of the document to be retrieved

[source,rust]
----
include::devguide:example$src/subdocument.rs[tag=combine,indent=0]
----

// Counters

include::{version-common}@sdk:shared:partial$documents.adoc[tag=counters1]




// NB for XDCR, add in something on CRDTs? (see Kleppmann) -
// https://martin.kleppmann.com/2017/04/24/json-crdt.html
// 
// Strong eventual consistency -
// https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type
//
// Maybe link https://jsonjoy.com/specs/json-crdt  ?




[source,rust]
----
include::devguide:example$src/binary.rs[tag=counterexample,indent=0]
----

include::{version-common}@sdk:shared:partial$documents.adoc[tag=counters2]

[source,rust]
----
include::devguide:example$src/concurrency.rs[tag=counterwithcas,indent=0]
----

include::{version-common}@sdk:shared:partial$documents.adoc[tag=counters3]


=== Use Cases

The SDK provides a high-level abstraction over the simple `incr()`/`decr()` of Couchbase Server's memcached binary protocol, using `collections.binary()`.
This enables you to work with counters using `get()` and `upsert()` operations -- allowing, _inter alia_, the use of durability options with the operations.
You will find several ways of working with counters https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/AsyncBinaryCollection.html[in the API docs].

// Expiry
include::{version-common}@sdk:shared:partial$documents.adoc[tag=expiration]
