= Querying with {sqlpp}
:page-toclevels: 2
:description: Parallel data management for complex queries over many records, using a familiar SQL-like syntax.
:nav-title: Querying with {sqlpp}
// :page-aliases: ROOT:n1ql-query,



[abstract]
{description}

include::{version-common}@sdk:shared:partial$n1ql-queries.adoc[tag=intro]


// Prepared Statements for Query Optimization
include::{version-common}@sdk:shared:partial$n1ql-queries.adoc[tag=prepared]

For the Rust SDK, the `adhoc` parameter should be set to `false` for a plan to be prepared, or a prepared plan to be reused.

[source,rust]
----
include::devguide:example$src/queries.rs[tag=adhocquery,indent=0]
----


== Indexes

The Couchbase query service makes use of xref:{version-server}@server:learn:services-and-indexes/indexes/indexes.adoc[_indexes_] in order to do its work.
Indexes replicate subsets of documents from data nodes over to index nodes, allowing specific data (for example, specific document properties) to be retrieved quickly, and to distribute load away from data nodes in xref:{version-server}@server:learn:services-and-indexes/services/services.adoc[MDS] topologies.

=== Query without Index

From Couchbase Server 7.6 onwards,
CRUD operations (such as `CREATE`, `INSERT`, and `SELECT`) and `JOIN` can be performed against the Query Service without an index (primary or secondary).
This uses a xref:server:learn:services-and-indexes/indexes/query-without-index.adoc#sequential-scans[sequential scan], relying on a KV range scan to deliver the keys.

Sequential scans are best suited to small collections where key order is unimportant, or where the overhead of maintaining an index can't be justified.
For larger collections and greater performance, define the appropriate indexes to speed up your queries.
For ordered document key operations, a primary index provides the same functionality, and will outperform a sequential scan.

Creating the right index, with the right keys, right order, and right expression is critical to query performance in any database system.
A Primary Index on the document keys will give you better search performance than trying to query without index,
but well-chosen secondary indexes will make all the difference to query performance.

=== Defining an Index

You can define a _primary index_ on a collection.
When a _primary_ index is defined you can issue non-covered (see below) queries on the bucket as well.
This includes using the `META` function in the queries.

[source,sqlpp]
----
CREATE PRIMARY INDEX ON `users`;
----

You can also define indexes over given document fields and then use those fields in the query:

[source,sqlpp]
----
CREATE INDEX ix_name ON `travel-sample`.inventory.hotel(name);
CREATE INDEX ix_email ON `travel-sample`.inventory.hotel(email);
----

This would allow you to query the _travel-sample_ bucket's hotel collection regarding a document's `name` or `email` properties, thus:

[source,sqlpp]
----
SELECT name, email
FROM `travel-sample`.inventory.hotel
WHERE name="Glasgow Grand Central" OR email="grandcentralhotel@example.com";
----

Indexes help improve the performance of a query.
When an index includes the actual values of all the fields specified in the query, the index _covers_ the query, and eliminates the need to fetch the actual values from the Data Service.
An index, in this case, is called a _covering index_, and the query is called a _covered_ query.
For more information, see xref:{version-server}@server:n1ql:n1ql-language-reference/covering-indexes.adoc[Covering Indexes].

You can also create and define indexes in the SDK using:

[source,rust]
----
include::devguide:example$src/queries.rs[tag=createindexes,indent=0]
----

== Index Building

Creating indexes on buckets with many existing documents can take a long time.
You can build indexes in the background, creating _deferred_ indexes.
The deferred indexes can be built together, rather than having to re-scan the entire bucket for each index.

[source,sqlpp]
----
CREATE PRIMARY INDEX ON `travel-sample`.inventory.hotel WITH {"defer_build": true};
CREATE INDEX ix_name ON `travel-sample`.inventory.hotel(name) WITH {"defer_build": true};
CREATE INDEX ix_email ON `travel-sample`.inventory.hotel(email) WITH {"defer_build": true};
BUILD INDEX ON `travel-sample`.inventory.hotel(`#primary`, `ix_name`, `ix_email`);
----

The indexes are not built until the `BUILD INDEX` statement is executed.
At this point, the server scans all of the documents in the `users` bucket, and indexes it for all of the applicable indexes (in this case, those that have a `name` or `email` field).

Building deferred indexes can also be done via the SDK:

[source,rust]
----
include::devguide:example$src/queries.rs[tag=deferredindexes,indent=0]
----

Note that the build step is still asynchronous, so `watchIndexes` is used to wait for the indexes to be completed.
"#primary" is the primary index.


// Index Consistency
include::{version-common}@sdk:shared:partial$n1ql-queries.adoc[tag=index-consistency]

The following options are available:

* `ScanConsistency::NotBounded`: Executes the query immediately, without requiring any consistency for the query.
If index-maintenance is running behind, out-of-date results may be returned.
* `ScanConsistency::AtPlus`: Executes the query, requiring indexes first to be updated to the timestamp of the last update.
If index-maintenance is running behind, the query waits for it to catch up.
* `ScanConsistency::RequestPlus`: Executes the query, requiring the indexes first to be updated to the timestamp of the current query-request.
If index-maintenance is running behind, the query waits for it to catch up.

For {sqlpp}, the default consistency is `NotBounded`.

* A {sqlpp} query using the default `NotBounded` scan consistency will not wait for any indexes to finish updating before running the query and returning results, meaning that results are returned quickly, but the query will not return any documents that are yet to be indexed.

* With scan consistency set to `RequestPlus`, all outstanding document changes and index updates are processed before the query is run.
Select this when consistency is always more important than performance.

* For a middle ground, `AtPlus` is a "read your own write" (RYOW) option, which means it just waits for the documents that you specify to be indexed.

Here's how to specify the `RequestPlus` scan consistency level:

[source,rust]
----
include::devguide:example$src/queries.rs[tag=request_plus_query,indent=0]
----

And the `AtPlus` level is represented with `QueryScanConsistency.ConsistentWith`:

[source,rust]
----
include::devguide:example$src/queries.rs[tag=atplus,indent=0]
----
